# Generated by Django 5.2.8 on 2025-12-30 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('todo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.CharField()),
                ('ai_response', models.CharField()),
                ('interaction_id', models.CharField(max_length=255, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(default='default', max_length=255)),
                ('previous_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_messages', to='todoapp.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_group', models.CharField()),
                ('project_name', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('intensity', models.CharField()),
                ('status', models.CharField()),
                ('entry_date_time', models.CharField()),
                ('ai_use', models.BooleanField(default=False)),
                ('group_task', models.BooleanField(default=False)),
                ('project_id', models.CharField(default='default', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
