# Generated by Django 5.2.8 on 2026-01-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_chatmessage_user_checkins_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='group_task',
        ),
    ]
