# Generated by Django 6.0 on 2026-01-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todos_group_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='interaction_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='previous_interaction',
        ),
    ]
